#if !canImport(ObjectiveC)
import XCTest

extension AlwaysTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlwaysTests = [
        ("testAlways", testAlways),
    ]
}

extension AndTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AndTests = [
        ("testAndDifferentTypes", testAndDifferentTypes),
        ("testAndSameType", testAndSameType),
        ("testOperator", testOperator),
    ]
}

extension BiPredicateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BiPredicateTests = [
        ("testBiPredicateFalse", testBiPredicateFalse),
        ("testBiPredicateTrue", testBiPredicateTrue),
        ("testCallableValue", testCallableValue),
    ]
}

extension NegateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NegateTests = [
        ("testNegate", testNegate),
        ("testNegateOperator", testNegateOperator),
    ]
}

extension NeverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NeverTests = [
        ("testNever", testNever),
    ]
}

extension OrTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrTests = [
        ("testOr", testOr),
        ("testOrOperator", testOrOperator),
    ]
}

extension PullbackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PullbackTests = [
        ("testPullback", testPullback),
    ]
}

extension XorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XorTests = [
        ("testXor", testXor),
    ]
}

extension ZipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ZipTests = [
        ("testZip", testZip),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AlwaysTests.__allTests__AlwaysTests),
        testCase(AndTests.__allTests__AndTests),
        testCase(BiPredicateTests.__allTests__BiPredicateTests),
        testCase(NegateTests.__allTests__NegateTests),
        testCase(NeverTests.__allTests__NeverTests),
        testCase(OrTests.__allTests__OrTests),
        testCase(PullbackTests.__allTests__PullbackTests),
        testCase(XorTests.__allTests__XorTests),
        testCase(ZipTests.__allTests__ZipTests),
    ]
}
#endif
