name: Swift

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  mac_test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
  linux_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build --tag predicate-testing .
        run: docker run --rm predicate-testing
